### ISSUE TITLE
failed to use debugger 

### ISSUE THREAD

**Issue by roife** [Jatana/FastOlympicCoding#2]
I'm using it on macOS and I'm wondering how I can use debugger as README.md said.

**Comment by Jatana** [comment]
Thank you for feedback!
To use debugger you only need lldb, the easiest way to get lldb is to install `Xcode` (you can install `Xcode` via `AppStore`)

To run program in debug mode press <kbd>ctrl+shift+b</kbd> to enable/disable debugger, 
if your program falls, you can see the line where it falls and variables in current frame.

More debug functional will be added soon.

**Comment by Galib35** [comment]
please build a debugger setup for Windows
