### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by rifatr** [Jatana/FastOlympicCoding#25]
CppFastOlympicCoding is a very nice and my favorite package. Due to some reasons, I had to reinstall my ubuntu 20.04 LTS operating system. Now I am trying to install CppFastOlympicCoding from last three days but it gives me this error all time(See at Picture below). 
![Screenshot from 2020-10-21 17-59-00](https://user-images.githubusercontent.com/71585953/97051454-0b64b780-15a1-11eb-84fd-623d1796d3b3.png)

I'd tried to download manually  form github but it also doesn't work.

**Comment by Jatana** [comment]
Hi!

When you tried to install it manually, have you renamed the folder to CppFastOlympicCoding?

Also, if you are facing an error, press ctrl+~ and paste the log output here.

**Comment by rifatr** [comment]
It's okay now. Donno what was happening.

**Comment by npanuhin** [comment]
> It's okay now. Donno what was happening.

You might want to close this issue then?)

**Comment by rifatr** [comment]
Yes.
