### ISSUE TITLE
The sidebar hide automatically?

### ISSUE THREAD

**Issue by livrth** [Jatana/FastOlympicCoding#26]
when I open the compile and run mode，the  right panel open，but the sidebar which in the left was hiden automatically.
Maybe that's the sublime's operation instead the FastOlympicCoding,
If FastOlympicCoding has this feature, I want to know how to set, and don't hide the sidebar automatically. 

Thanks.

**Comment by npanuhin** [comment]
Hello!
This feature was added in # 16, however, no new tag was created to update the package on packagecontrol.io.
Maybe @Jatana can do this.

**Comment by Jatana** [comment]
Released https://github.com/Jatana/FastOlympicCoding/releases/tag/v1.4.10

**Comment by lazydooog** [comment]
> Hi
> 
> The feature has been released - https://github.com/Jatana/FastOlympicCoding/releases/tag/v1.4.10

Thank you very much!

**Comment by npanuhin** [comment]
How about closing this issue?)

**Comment by livrth** [comment]
> How about closing this issue?)

sorry i forgot, now it can be closed
