### ISSUE TITLE
Suggestion to add a "delete all" button beside "next test" button

### ISSUE THREAD

**Issue by AnonySharma** [Jatana/FastOlympicCoding#31]
That "delete all" button delete the tests file. 

![Screenshot from 2020-12-31 04-07-14](https://user-images.githubusercontent.com/56964985/103384837-e56a0f00-4b1d-11eb-8360-08b109a1eca3.png)

**Comment by AnonySharma** [comment]
Another option is that, a new key-binding can be added to delete all the test cases.

**Comment by Jatana** [comment]
You can press <kbd>ctrl+a</kbd> <kbd>ctrl+d</kbd> (Windows/Linux) <kbd>cmd+a</kbd> <kbd>ctrl+d</kbd> (OSX) to delete all tests.

**Comment by AnonySharma** [comment]
Oh okay, Thanks for letting me know.
I'm closing the issue.
