### ISSUE TITLE
How to change the key bindings

### ISSUE THREAD

**Issue by pvcodes** [Jatana/FastOlympicCoding#41]
Hey, TBH we can change the default key binding for sure, but can't figure out how. So please tell and also put it to the docs or readme file

**Comment by j0k4rX** [comment]
Go to package manager directory, 
There you will find the default keymaps for win, Linux, osx. 
Then change according to your own preferences. 
Good luck!

**Comment by pvcodes** [comment]
Thanks!

**Comment by akib35** [comment]
thanks

**Comment by Garavitey** [comment]
I can't follow the steps. can someone explain it in detail? I want to change ctrl + b to cmd + ".
