### ISSUE TITLE
Plugin not working in linux

### ISSUE THREAD

**Issue by Sriram-L** [Jatana/FastOlympicCoding#43]
I tried to run a simple code but the output is not getting printed
Following is the issue...
![Screenshot from 2021-04-21 12-36-03](https://user-images.githubusercontent.com/60982834/115511443-77994d00-a29e-11eb-86c5-3fa35102f790.png)

Kindly look on this

**Comment by qumusabel** [comment]
Add `\n`?

**Comment by Sriram-L** [comment]
@qumusabel yes as you mentioned it is about `\n`. But there is a small problem which I have found recently. It seems in the -run file the keypad_enter button doesnt work properly. But the normal enter button works fine and I do see the output.
