### ISSUE TITLE
cin not working for sublime text 4

### ISSUE THREAD

**Issue by Devashish-Bawa** [Jatana/FastOlympicCoding#56]
![image](https://user-images.githubusercontent.com/57852149/133293316-9fe0b63e-a757-4fbb-8d3f-9f010b662e6b.png)

as you can see in this file only 1 variable is taking input but it taking infinite inputs and not showing any inputs.

**Comment by Devashish-Bawa** [comment]
COUT is working, only if cout statement is there.

**Comment by Jatana** [comment]
Hi! Could you restart Sublime Text, press ```ctrl+~```, and try to run the program again. Paste the log here.

**Comment by Devashish-Bawa** [comment]
![image](https://user-images.githubusercontent.com/57852149/133823442-abbc2dd7-4d09-4906-9232-80ee4231aaec.png)



This is showing in console, while running :- 
warning: mnemonic R not found in menu caption FastOlympicCoding
warning: mnemonic R not found in menu caption FastOlympicCoding
[FastOlympicCoding] session saved
[FastOlympicCoding] process terminating error
[FastOlympicCoding] session saved
[FastOlympicCoding] process terminating error
[FastOlympicCoding] session saved
[FastOlympicCoding] process terminating error
[FastOlympicCoding] session saved

**Comment by Devashish-Bawa** [comment]
@Jatana any solution ??

**Comment by Jatana** [comment]
What OS are you using?

**Comment by Devashish-Bawa** [comment]
Windows 10

**Comment by Devashish-Bawa** [comment]
@Jatana did u get any solution for this ?

**Comment by Jatana** [comment]
Create file main.py and paste code in it from here — https://gist.github.com/Jatana/0d3255a5c83aead04c05695a75ad52f0. Then run it from the console via `python3 main.py`. Paste the output here.

**Comment by Devashish-Bawa** [comment]
![image](https://user-images.githubusercontent.com/57852149/144252381-294a5715-a592-447d-bc61-219c63a9d24e.png)


i am getting error while using this command!!

**Comment by Jatana** [comment]
You should run it from the Window's console, not the Sublime's one. Or paste the following to the Sublime's console
```
import subprocess
subprocess.check_output('python3 "D://CPP/CF/mast.py"', shell=True)
```

**Comment by Devashish-Bawa** [comment]
@Jatana  This is windows console output
![image](https://user-images.githubusercontent.com/57852149/144565686-c46786c2-84d3-4c38-bed8-c817d70622da.png)

@Jatana this is sublime's console output:-
![image](https://user-images.githubusercontent.com/57852149/144565884-9d7f25f4-ffea-4a60-b14f-9a04b66d5186.png)

**Comment by Jatana** [comment]
Paste this https://gist.github.com/Jatana/476b9a0260e454b47c76f3cc25969f08 to main.py, and run it from the Window's console.

**Comment by Jatana** [comment]
Also, paste this https://gist.github.com/Jatana/23d32476d32c03bfd211ee2c0023a7e9 to main.py, and run it from the Window's console. Attach the screenshot of the result.

**Comment by Devashish-Bawa** [comment]
> Paste this https://gist.github.com/Jatana/476b9a0260e454b47c76f3cc25969f08 to main.py, and run it from the Window's console.

![image](https://user-images.githubusercontent.com/57852149/144801788-a6f0b1eb-5ee1-4bd7-8fa9-1273d5e9b09a.png)

@Jatana here is the screenshot

**Comment by Devashish-Bawa** [comment]
> Also, paste this https://gist.github.com/Jatana/23d32476d32c03bfd211ee2c0023a7e9 to main.py, and run it from the Window's console. Attach the screenshot of the result.

![image](https://user-images.githubusercontent.com/57852149/144801932-7df5804e-6d35-40dc-aedd-d56eca552535.png)

@Jatana here is the screenshot of the second one

**Comment by Devashish-Bawa** [comment]
Leave it!! I have started using cp-editor its good! :)
Thanks for all the help.

**Comment by Devashish-Bawa** [comment]
Leave it!! I have started using cp-editor its good! :)
Thanks for all the help.
