### ISSUE TITLE
Error trying to parse file

### ISSUE THREAD

**Issue by liupei101** [Jatana/FastOlympicCoding#6]
After downloading plugin into packages, error occurred as shown in picture below.

![_20180720173917](https://user-images.githubusercontent.com/15051403/42995618-e3d0ef60-8c43-11e8-898e-836a85581a0d.png)

I have no idea to deal with it!

**Comment by Jatana** [comment]
Fixed, f6378c2.

**Comment by liupei101** [comment]
Thx !
