### ISSUE TITLE
How do I use the class autocompletion? 

### ISSUE THREAD

**Issue by xlbert** [Jatana/FastOlympicCoding#7]
Is there a guide somewhere on how to use the class autocompletion function of the package?

**Comment by Jatana** [comment]
Well, it is a very intuitive thing. I think you can understand all functionality from the example image.

Each class constists of template size and letter which representing it. See more information in the [settings](https://github.com/Jatana/FastOlympicCoding#settings).
So, you only need to type this letters as shown in the example image.

**Comment by Prabhat-IIT** [comment]
The documentation is still not clear about this. What does template size represent and how can I add my own template?

**Comment by whohet** [comment]
I am facing a problem in the autocompletion feature(Windows). Whenever, i try to autocomplete the recommened stuff for eg. vec to vector<> ,then the std:: appears with it too (i.e std::vector<char>) and it becomes too annoying. I have tried to change the settings but I couldn't succeed. 
See the below images for betterr understandibilty.
![Screenshot (38)](https://user-images.githubusercontent.com/56436879/91845902-a020f800-ec77-11ea-949a-215fdc9d130f.png)
![Screenshot (39)](https://user-images.githubusercontent.com/56436879/91845916-a616d900-ec77-11ea-9e64-5e797ae159a8.png)

**Comment by npanuhin** [comment]
I have a possible solution for your problem (disabling this snippet):

1) Get the [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer) from Package Control
2) `Ctrl + Shift + P` -> `PackageResourceViewer: Extract package` -> choose `C++` -> after this press `Enter` to start extraction
3) Navigate to `C:\Program Files\Sublime Text 3\Packages` (where Sublime is installed)
4) Delete file `C++.sublime-package`
5) Go to `Preferences` -> `Browse packages` -> `C++` folder (PackageResourceViewer extracted it here) -> `Snippets` folder -> delete (or edit) file `std-vector-(v).sublime-snippet`

You can read about Sublime snippets [here](https://docs.sublimetext.io/guide/extensibility/snippets.html)

**Comment by whohet** [comment]
> @whohet, I have a possible solution for your problem (disabling this snippet):
> 
> 1. Get the [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer) from Package Control
> 2. `Ctrl + Shift + P` -> `PackageResourceViewer: Extract package` -> choose `C++` -> after this press `Enter` to start extraction
> 3. Navigate to `C:\Program Files\Sublime Text 3\Packages` (where Sublime is installed)
> 4. Delete file `C++.sublime-package`
> 5. Go to `Preferences` -> `Browse packages` -> `C++` folder (PackageResourceViewer extracted it here) -> `Snippets` folder -> delete (or edit) file `std-vector-(v).sublime-snippet`
> 
> You can read about Sublime snippets [here](https://docs.sublimetext.io/guide/extensibility/snippets.html)

Hi, there! Thanks for the reply...I will surely see to it.

**Comment by npanuhin** [comment]
Actually this snippet has nothing to do with **FastOlympicCoding** - it is part of the standard **C++** package.
