### ISSUE TITLE
is fastOlympicCoding removed from sublime ?

### ISSUE THREAD

**Issue by mindFlayer123** [Jatana/FastOlympicCoding#73]

**Comment by mindFlayer123** [comment]
ctrl + alt + B not working

**Comment by FatemaAkther2** [comment]
same here

**Comment by FatemaAkther2** [comment]
what's the problem?

**Comment by mindFlayer123** [comment]
Somewhat with author's packages...they are not updated so might be outdated and removed by organization...

**Comment by backermanbd** [comment]
No. It is not removed from sublime.
Previous versions are working fine. 


> ctrl + alt + B not working

Yes, it's not working in latest **v1.4.11**

**Comment by GEJXD** [comment]
I'm sorry to bother you, this plugin doesn't seem to be working right now.

**Comment by Jatana** [comment]
There was a problem in the v1.4.11 release with an import of a module which was not present. Everything should be fine in the latest release (v1.4.12). The packagecontrol soon will update the plugin version from v1.4.11 to v1.4.12. Sorry for the inconvenience.

**Comment by mindFlayer123** [comment]
@Jatana Thanks, :), pls inform once after updating...

**Comment by DeveloperKev** [comment]
> There was a problem in the v1.4.11 release with an import of a module which was not present. Everything should be fine in the latest release (v1.4.12). The packagecontrol soon will update the plugin version from v1.4.11 to v1.4.12. Sorry for the inconvenience.

pls change the description to "sublime text 4".

**Comment by sachin-0102** [comment]
Is there any way to fix it @Jatana or it will happen on its own after the update?

**Comment by Jatana** [comment]
Packagecontrol has update the version. Run `Package Control: Upgrade Package` and restart Sublime Text. After that, everything should work normally.

**Comment by DeveloperKev** [comment]
> Packagecontrol has updated the version. Run `Package Control: Upgrade Package` and restart Sublime Text. After that, everything should work normally.

Thanks a lot!
btw when did u start developing this package from scratch? and the gui is top notch.
did u do it yourself standalone?

**Comment by Jatana** [comment]
> > Packagecontrol has updated the version. Run `Package Control: Upgrade Package` and restart Sublime Text. After that, everything should work normally.
> 
> Thanks a lot! btw when did u start developing this package from scratch? and the gui is top notch. did u do it yourself standalone?

I started developing it around 5 years ago. I'm glad that you liked it. The most of the plugin's features were developed by me. At first, I was creating this plugin to use solely by my own. Later, I decided to add it to Packagecontrol in case someone also would find it useful. Of course, issues and pull requests from the community helped to catch bugs and improve existing features.
