### ISSUE TITLE
FastOlympicCoding isn't working!

### ISSUE THREAD

**Issue by DeveloperKev** [Jatana/FastOlympicCoding#74]
Hi @Jatana ,
it is very heartbreaking.

**Comment by sachin-0102** [comment]
same for me. Not working

**Comment by zltkh** [comment]
there is a solution while @Jatana will not fix this bug. Previously remove the plugin from Package Control. Download older version by link https://github.com/Jatana/FastOlympicCoding/tree/3e058e5915ffcb2e5f9fb1673bd34945c46e0940 , unzip it and rename main folder to FastOlympicCoding. Then go to Sublime Text/Packages, copy and paste FastOlympicCoding and reload SublimeText

**Comment by DeveloperKev** [comment]
> there is a solution while @Jatana will not fix this bug. Previously remove the plugin from Package Control. Download older version by link https://github.com/Jatana/FastOlympicCoding/tree/3e058e5915ffcb2e5f9fb1673bd34945c46e0940 , unzip it and rename main folder to FastOlympicCoding. Then go to Sublime Text/Packages, copy and paste FastOlympicCoding and reload SublimeText

Fixed.
