### ISSUE TITLE
custom key bindings

### ISSUE THREAD

**Issue by ghost** [Jatana/FastOlympicCoding#81]
Hi, long time no see!

I've been using this plugin for several years, and it's a very good work. But I recently switched to macOS, so I'm more used to using the `command + b` or `command + shift + b` shortcut to compile and run. But it seems that there is no key binding setting option, so I want to know how to modify the key binding?

There is also a small question, can this plugin natively support Apple's Arm chip?

Thanks for answering!

**Comment by 8ovehat1r** [comment]
I also have the same problem. Hope the owner to fix it.

**Comment by 8ovehat1r** [comment]
> Hi, long time no see!
> 
> I've been using this plugin for several years, and it's a very good work. But I recently switched to macOS, so I'm more used to using the `command + b` or `command + shift + b` shortcut to compile and run. But it seems that there is no key binding setting option, so I want to know how to modify the key binding?
> 
> There is also a small question, can this plugin natively support Apple's Arm chip?
> 
> Thanks for answering!

I have found the solution.

You can open the dictionary the plugin places, then you can find a folder called "Default (OSX).sublime-keymap", then you can modify it.

另外你好像是中国人，我拿中文再说一遍防止英文水平太烂（

你打开插件目录找到这个插件里面有个 Default (OSX).sublime-keymap 在那里面改就可以了

**Comment by ghost** [comment]
> 

thank you very much!
